import { useState, type FormEvent } from 'react'
import { ArrowUpRight, CheckCircle2, Leaf, Mail, MapPin, Phone } from 'lucide-react'
import { motion } from 'framer-motion'
import { readContent } from './store'

const rise = { initial:{opacity:0,y:22}, whileInView:{opacity:1,y:0}, viewport:{once:true,margin:'-80px'}, transition:{duration:.65} }
export default function DynamicContact() {
  const contact=readContent().contact; const [sent,setSent]=useState(false)
  const submit=async (event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const data=new FormData(form);try{const response=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:data.get('name'),email:data.get('email'),phone:data.get('phone'),subject:data.get('subject'),message:data.get('message')})});if(!response.ok)throw new Error();setSent(true);form.reset()}catch{window.alert(`We could not send your message right now. Please call ${contact.phone}.`)}}
  const phoneHref=`tel:${contact.phone.replace(/[^0-9+]/g,'')}`
  return <section id="contact" className="section contact-section"><div className="shell"><div className="split-heading"><motion.div {...rise}><p className="eyebrow">{contact.eyebrow}</p><h2>{contact.title}<br/><em>{contact.emphasizedTitle}</em></h2></motion.div><motion.a href={phoneHref} className="text-link heading-side" {...rise}>Call for a free quote <ArrowUpRight size={16}/></motion.a></div><div className="contact-layout"><motion.div className="contact-details contact-panel" {...rise}><div className="panel-top"><span className="panel-mark"><Leaf size={17}/></span><span>{contact.company}</span></div><div className="panel-copy"><p className="panel-kicker">PROTECTION, MADE PERSONAL</p><h3>Feel confident<br/><em>about tomorrow.</em></h3><p>We take the time to understand what matters to you, then build a policy around it.</p></div><div className="panel-proof"><strong>10+</strong><span>years helping<br/>our community</span><i></i><strong>15+</strong><span>insurance companies<br/>to choose from</span></div><div className="panel-contact"><a href={phoneHref} className="contact-line"><Phone size={18}/>{contact.phone}</a><a href={`mailto:${contact.email}`} className="contact-line"><Mail size={18}/>{contact.email}</a><div className="contact-line"><MapPin size={18}/><span>{contact.address}<br/>{contact.hours}</span></div></div><a href={phoneHref} className="panel-cta">Talk to an agent <ArrowUpRight size={17}/></a></motion.div><motion.div className="contact-card" {...rise} transition={{...rise.transition,delay:.12}}><div className="form-top"><span>REQUEST A QUOTE</span><p>{contact.formTitle}</p></div><form onSubmit={submit}><label>Your Name *<input name="name" placeholder="Your Name" required/></label><label>E-mail Address *<input type="email" name="email" placeholder="E-mail Address" required/></label><label>Phone *<input name="phone" placeholder="(000) 000-0000" required/></label><label>Subject<input name="subject" placeholder="What can we help with?"/></label><label>Message *<textarea name="message" rows={5} placeholder="Tell us what you need covered" required/></label><button type="submit" className="form-submit">{sent?<><CheckCircle2 size={17}/> Message received</>:<>Send message <ArrowUpRight size={17}/></>}</button>{sent&&<motion.p className="form-success" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}>{contact.successMessage}</motion.p>}</form></motion.div></div></div></section>
}
